Partindo do ponto em que os dados já estão limpos, chegamos à etapa de "exploração dos dados". Primeiramente, pretendo entender quais são as colunas, que dados elas trazem e suas necessidades para a análise como um todo. Para isso podemos usar alguns comandos:

In [5]:
# Imports
import numpy as np
import pandas as pd

df = pd.read_csv("../../data/processed/olist_super_dataset.csv")

In [17]:
# Análise exploratória dos dados

df.head(12)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,tempo_entrega_dias,atraso_entrega,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,payment_value,review_score,receita_liquida
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,False,...,268.0,4.0,500.0,19.0,8.0,13.0,housewares,38.71,4.0,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,False,...,178.0,1.0,400.0,19.0,13.0,19.0,perfumery,141.46,4.0,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,False,...,232.0,1.0,420.0,24.0,19.0,21.0,auto,179.12,5.0,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,False,...,468.0,3.0,450.0,30.0,10.0,20.0,pet_shop,72.20,5.0,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,False,...,316.0,4.0,250.0,51.0,15.0,15.0,stationery,28.62,5.0,28.62
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,16.0,False,...,608.0,1.0,7150.0,65.0,10.0,65.0,auto,175.26,4.0,175.26
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09,NaN,False,...,NaN,NaN,600.0,35.0,35.0,15.0,other,65.95,2.0,65.95
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,9.0,False,...,956.0,1.0,50.0,16.0,16.0,17.0,auto,75.16,5.0,75.16
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06,9.0,False,...,432.0,2.0,300.0,35.0,35.0,15.0,furniture_decor,35.95,1.0,35.95
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,18.0,False,...,527.0,1.0,9750.0,42.0,41.0,42.0,office_furniture,169.76,5.0,169.76
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,12.0,False,...,450.0,1.0,9000.0,42.0,12.0,39.0,garden_tools,259.06,1.0,129.53
11,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,12.0,False,...,450.0,1.0,9000.0,42.0,12.0,39.0,garden_tools,259.06,1.0,129.53

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111744 entries, 0 to 111743
Data columns (total 32 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       111744 non-null  object
 1   customer_id                    111744 non-null  object
 2   order_status                   111744 non-null  object
 3   order_purchase_timestamp       111744 non-null  object
 4   order_approved_at              111729 non-null  object
 5   order_delivered_carrier_date   111381 non-null  object
 6   order_delivered_customer_date  110189 non-null  object
 7   order_estimated_delivery_date  111744 non-null  object
 8   tempo_entrega_dias             110189 non-null  float64
 9   atraso_entrega                 111744 non-null  bool
 10  customer_unique_id             111744 non-null  object
 11  customer_zip_code_prefix       111744 non-null  int64
 12  customer_city                  111744 non-null  object
 13  customer_state                 111744 non-null  object
 14  order_item_id                  111741 non-null  float64
 15  product_id                     111741 non-null  object
 16  seller_id                      111741 non-null  object
 17  shipping_limit_date            111741 non-null  object
 18  price                          111741 non-null  float64
 19  freight_value                  111741 non-null  float64
 20  product_category_name          110165 non-null  object
 21  product_name_lenght            110165 non-null  float64
 22  product_description_lenght     110165 non-null  float64
 23  product_photos_qty             110165 non-null  float64
 24  product_weight_g               111723 non-null  float64
 25  product_length_cm              111723 non-null  float64
 26  product_height_cm              111723 non-null  float64
 27  product_width_cm               111723 non-null  float64
 28  product_category_name_english  111741 non-null  object
 29  payment_value                  111741 non-null  float64
 30  review_score                   110825 non-null  float64
 31  receita_liquida                111741 non-null  float64
dtypes: bool(1), float64(14), int64(1), object(16)
memory usage: 26.5+ MB

Conforme podemos obervar, temos muitas variáveis (colunas) e nem todas são de total relevância para a análise - 32 colunas quando escrevi essa etapa.

In [11]:
df.describe()

,tempo_entrega_dias,customer_zip_code_prefix,order_item_id,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,payment_value,review_score,receita_liquida
count,110189.000000,111744.000000,111741.000000,111741.000000,111741.000000,110165.000000,110165.000000,110165.000000,111723.000000,111723.000000,111723.000000,111723.000000,111741.000000,110825.000000,111741.000000
mean,12.007342,35158.642692,1.197099,120.222227,19.976015,48.805437,787.920492,2.211483,2093.083036,30.150444,16.570178,22.989483,179.483998,4.053424,140.198243
std,9.451153,29873.385388,0.704082,182.575481,15.750195,10.008509,651.854412,1.723395,3749.883454,16.144407,13.422014,11.694874,270.753277,1.369230,189.628686
min,0.000000,1003.000000,1.000000,0.850000,0.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000,9.590000,1.000000,6.080000
25%,6.000000,11320.000000,1.000000,39.900000,13.080000,42.000000,348.000000,1.000000,300.000000,18.000000,8.000000,15.000000,65.600000,4.000000,55.220000
50%,10.000000,24348.000000,1.000000,74.900000,16.270000,52.000000,603.000000,1.000000,700.000000,25.000000,13.000000,20.000000,114.340000,5.000000,92.210000
75%,15.000000,59064.000000,1.000000,134.900000,21.150000,57.000000,989.000000,3.000000,1800.000000,38.000000,20.000000,30.000000,194.990000,5.000000,157.680000
max,209.000000,99990.000000,21.000000,6735.000000,409.680000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000,13664.080000,5.000000,6929.310000

In [14]:
df["customer_id"].unique()

array(['9ef432eb6251297304e76186b10a928d',
       'b0830fb4747a6c6d20dea0b8c802d7ef',
       '41ce2a54c0b03bf3443c3d931a367089', ...,
       '1aa71eb042121263aafbe80c1b562c9c',
       'b331b74b18dc79bcdf6532d51e1637c1',
       'edb027a75a1449115f6b43211ae02a24'], shape=(97899,), dtype=object)

In [16]:
df["customer_zip_code_prefix"].unique()

array([ 3149, 47813, 75265, ..., 83870,  5127, 45920], shape=(14949,))